#!/usr/bin/env python3
"""Generate http_l1glyf_js.c from web/l1glyf_builder.js + level1_data.c"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILDER = ROOT / "web" / "l1glyf_builder.js"
LEVEL1_C = ROOT / "level1_data.c"
OUT_C = ROOT / "http_l1glyf_js.c"
OUT_H = ROOT / "http_l1glyf_js.h"


def parse_level1(level1_c: Path) -> list[int]:
    text = level1_c.read_text(encoding="utf-8", errors="ignore")
    return [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]+", text)]


def main() -> None:
    level1 = parse_level1(LEVEL1_C)
    builder = BUILDER.read_text(encoding="utf-8")
    arr = ",".join(f"0x{cp:x}" for cp in level1)
    injected = builder.replace(
        "var LEVEL1_CHARS = window.__LEVEL1_CHARS__ || [];",
        f"var LEVEL1_CHARS = [{arr}];",
        1,
    )
    data = injected.encode("utf-8")

    lines = [
        "/* Auto-generated by tools/gen_l1glyf_web_js.py — do not edit */",
        '#include "http_l1glyf_js.h"',
        "",
        "const unsigned char http_l1glyf_js[] = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int http_l1glyf_js_len = {len(data)};")
    lines.append("")
    OUT_C.write_text("\n".join(lines), encoding="utf-8")

    OUT_H.write_text(
        "\n".join(
            [
                "#ifndef HTTP_L1GLYF_JS_H",
                "#define HTTP_L1GLYF_JS_H",
                "",
                "extern const unsigned char http_l1glyf_js[];",
                "extern const unsigned int http_l1glyf_js_len;",
                "",
                "#endif",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_C} ({len(data):,} bytes JS)")
    print(f"Wrote {OUT_H}")


if __name__ == "__main__":
    main()
