#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_gbk_table.py — 生成 GBK -> Unicode 映射表 (gbk_table.c)

GBK 双字节编码：
  lead byte : 0x81 .. 0xFE        (126 个)
  trail byte: 0x40 .. 0x7E ∪ 0x80 .. 0xFE   (3*19 + 0x7E-0x40+1 = 190 个，跳过 0x7F)

扁平索引方式 (与 gbk.c 中 gbk_index() 一致):
  trail:  0x40..0x7E -> 0..62      (63 个，跳过 0x7F)
          0x80..0xFE -> 63..189    (127 个)
  idx = (lead - 0x81) * 190 + trail_idx

总条目数: 126 * 190 = 23940
非法/未分配码位统一映射为 0（解码侧兜底为空格）。

用法:  python gen_gbk_table.py
输出:  ../gbk_table.inc   (.inc 后缀避免被 Makefile *.c glob 单独编译)
"""

import os
import sys

# GBK 全部 codepoint 映射（Python 内置 gbk codec 即 GB18030 子集）
def build_table():
    # lead: 0x81..0xFE, trail: 0x40..0x7E ∪ 0x80..0xFE
    leads = list(range(0x81, 0xFF))           # 0x81..0xFE
    trails = list(range(0x40, 0x7F)) + list(range(0x80, 0xFF))  # 跳过 0x7F

    table = [0] * (len(leads) * len(trails))  # 0 = 非法，解码兜底空格

    for li, lead in enumerate(leads):
        for ti, trail in enumerate(trails):
            raw = bytes([lead, trail])
            try:
                # strict 模式：仅完整合法的 GBK 双字节
                uni = raw.decode('gbk')
            except (UnicodeDecodeError, LookupError):
                continue
            if len(uni) != 1:
                continue
            cp = ord(uni)
            if cp < 0x80:
                # GBK 双字节不会映射到 ASCII，跳过（保留 0）
                continue
            idx = li * len(trails) + ti
            table[idx] = cp
    return table, len(leads), len(trails)


def main():
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            '..', 'gbk_table.inc')
    out_path = os.path.normpath(out_path)

    table, n_lead, n_trail = build_table()

    total = n_lead * n_trail
    valid = sum(1 for v in table if v != 0)

    lines = []
    lines.append('/* Auto-generated by tools/gen_gbk_table.py — DO NOT EDIT. */')
    lines.append('/* GBK -> Unicode flat table.')
    lines.append(' * Index = (lead-0x81)*190 + trail_idx')
    lines.append(' * trail_idx: 0x40..0x7E -> 0..62, 0x80..0xFE -> 63..189 (skip 0x7F)')
    lines.append(' * Total entries: %d, valid: %d. 0 = illegal (decode falls back to space). */' % (total, valid))
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append('#define GBK_TABLE_TOTAL  %d' % total)
    lines.append('#define GBK_TRAIL_COUNT  %d' % n_trail)
    lines.append('')
    lines.append('/* placed in PSRAM (.psram_data) — keeps SRAM (412KB) free. */')
    lines.append('__attribute__((section(".psram_data"))) const uint16_t g_gbk_to_uni[GBK_TABLE_TOTAL] = {')

    per_line = 8
    for i in range(0, total, per_line):
        chunk = table[i:i + per_line]
        lines.append('    ' + ','.join('0x%04X' % v for v in chunk) + ',')
    lines.append('};')
    lines.append('')

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print('Generated %s' % out_path)
    print('  entries=%d valid=%d (%.1f%%) size=%d bytes'
          % (total, valid, 100.0 * valid / total, total * 2))


if __name__ == '__main__':
    main()
